version: '2.0'

services:

  servidorWeb:
    container_name: SiCi-web-server
    build:
      context: SiCi/App
    volumes:
    - SiCi/app/:/var/www/html
    ports:
    - 83:80
    depends_on:
      - servidorBD

  servidorBD:
    container_name: SiCi-database-server
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
          - SiCi/MySQL:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: SiCi
    ports: 
      -"3310:3306"
    
  


